### ISSUE TITLE
Straight line pencil tool

### ISSUE THREAD

**Issue by xsot** [btzy/circuit-sandbox#4]
The current pencil tool which enables free form drawing is not ergonomic for circuit design. We should optimize the pencil tool for drawing horizontal and vertical lines.

**Comment by btzy** [comment]
The proposed pencil tool should work as follows:

- The pencil tool draws a polyline (multiple straight lines connected at their endpoints to form a chain)
- Mouse down with an input handle bound to the Pencil will start the action
- Mouse down and mouse up events both add a new point to the polyline (including the initial mouse down)
- If 'Shift' is not pressed on mouse up terminate the action after adding the mouse up point
- (Should happen without explicit code) Mouse down followed by mouse up on the same point will ignore the duplicate point for the polyline (but action might still be terminated if 'Shift' is not pressed)
